language: erlang
script: "make"
notifications:
  email: false
otp_release:
  - R16B03-1
before_install:
  # Download and install automake-1.14.1, required by ISA-L
  - curl "http://ftp.gnu.org/gnu/automake/automake-1.14.1.tar.gz" > automake-1.14.1.tar.gz
  - tar -zxvf automake-1.14.1.tar.gz
  - (cd automake-1.14.1 && ./configure && make -j4 && sudo make install)
  # Download and install autoconf-2.69, required by ISA-L
  - curl "http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz" > autoconf-2.69.tar.gz
  - tar -zxvf autoconf-2.69.tar.gz
  - (cd autoconf-2.69 && ./configure && make -j4 && sudo make install)
  # Download and install yasm-1.2.0, required by ISA-L
  - curl "http://www.tortall.net/projects/yasm/releases/yasm-1.2.0.tar.gz" > yasm-1.2.0.tar.gz
  - tar -zxvf yasm-1.2.0.tar.gz
  - (cd yasm-1.2.0 && ./configure && make -j4 && sudo make install)

  - sudo apt-get install -y libtool
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
