language: erlang
script: "make"
notifications:
  email: false
otp_release:
  - R16B03-1
before_install:
  - sudo apt-get install -y automake autoconf libtool yasm
install:
  - sudo apt-get install -y build-essential cmake check
